openapi: 3.0.0
info:
  title: Chess
  description: Chess app API
  version: 0.1.9

servers:
  - url: https://chess-back-production-98c9.up.railway.app/api
    description: production server
  - url: http://localhost:4000/api
    description: local server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /register:
    post:
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
                repeatPassword:
                  type: string
                redirectLink:
                  type: string
      responses:
        "201":
          description: user register successfully
